[[redirects]]
  from = "/.well-known/webfinger"
  to = "/.well-known/webfinger.json"

[[headers]]
  for = "/*"
  [headers.values]
    Link = '''
    </.well-known/webfinger.json>; rel="lrdd"; type="application/jrd+json",
    <https://webmention.io/lindsaykwardell.com/webmention>; rel="webmention",
    <https://webmention.io/lindsaykwardell.com/xmlrpc>; rel="pingback"'''

[[headers]]
  for = "/@lindsay/*"
  [headers.values]
    cache-control = '''
    max-age=604800,
    public'''

[[headers]]
  for = "/blog/*"
  [headers.values]
    cache-control = '''
    max-age=14400,
    public'''
