[[redirects]]
  from = "/.well-known/webfinger"
  to = "/.well-known/webfinger.json"

[[headers]]
  for = "/@lindsay/*"
  [headers.values]
    cache-control = '''
    max-age=604800,
    public'''

[[headers]]
  for = "/blog/*"
  [headers.values]
    cache-control = '''
    max-age=14400,
    public'''