[[redirects]]
  from = "/.well-known/webfinger"
  to = "/.well-known/webfinger.json"

[[redirects]]
  from = "/shows"
  to = "/blog"
  status = 301

[[redirects]]
  from = "/shows/*"
  to = "/blog"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    Link = '''
    </.well-known/webfinger.json>; rel="lrdd"; type="application/jrd+json",
    <https://webmention.io/www.lindsaykwardell.com/webmention>; rel="webmention"'''

[[headers]]
  for = "/@lindsay/*"
  [headers.values]
    cache-control = '''
    max-age=604800,
    public'''

[[headers]]
  for = "/blog/*"
  [headers.values]
    cache-control = '''
    max-age=14400,
    public'''
