backend:
  name: git-gateway
  branch: master

media_folder: static/blog
public_folder: /blog
site_url: https://lindsaykwardell.com
display_url: https://lindsaykwardell.com
logo_url: https://lindsaykwardell.com/favicon.png

collections:
  - name: 'post'
    label: 'Post'
    folder: 'content/posts'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Header Image', name: 'image', widget: 'image' }
      - { label: 'Snippet', name: 'snippet', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
